// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWioRgL3_roT5rJLbrIA41G26HKlE2Omw',
    appId: '1:962669561151:web:9d1d8031b0965e34093f8a',
    messagingSenderId: '962669561151',
    projectId: 'canya-prod',
    authDomain: 'canya-prod.firebaseapp.com',
    storageBucket: 'canya-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7YhC6NEL-m105s04O3S3lu7I4504sEc',
    appId: '1:962669561151:android:582245ce837ddf63093f8a',
    messagingSenderId: '962669561151',
    projectId: 'canya-prod',
    storageBucket: 'canya-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_p8ZBLjrvF8GzC6mafpdr-hRbtTWD30',
    appId: '1:962669561151:ios:764958dc5aeb562e093f8a',
    messagingSenderId: '962669561151',
    projectId: 'canya-prod',
    storageBucket: 'canya-prod.firebasestorage.app',
    iosClientId: '962669561151-nct2u3i3nnu26ecclupo7mamlvf6i5pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.canya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_p8ZBLjrvF8GzC6mafpdr-hRbtTWD30',
    appId: '1:962669561151:ios:764958dc5aeb562e093f8a',
    messagingSenderId: '962669561151',
    projectId: 'canya-prod',
    storageBucket: 'canya-prod.firebasestorage.app',
    iosClientId: '962669561151-nct2u3i3nnu26ecclupo7mamlvf6i5pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.canya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWioRgL3_roT5rJLbrIA41G26HKlE2Omw',
    appId: '1:962669561151:web:d7e11baae15b9a79093f8a',
    messagingSenderId: '962669561151',
    projectId: 'canya-prod',
    authDomain: 'canya-prod.firebaseapp.com',
    storageBucket: 'canya-prod.firebasestorage.app',
  );
}
